---
apiVersion: v1
kind: Service
metadata:
  name: demo1
  namespace: test-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo_mapping
      ambassador_id: ambassador-1
      prefix: /demo/
      service: demo1.test-svc
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  joint_1_mapping
      ambassador_id: 
      - ambassador-1
      - ambassador-2     
      prefix: /demo/
      headers:
        x-demo-mode: joint
      service: demo1.test-svc
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  should_not_appear_1
      prefix: /joint/
      service: demo1.test-svc
spec:
  selector:
    app: demo1
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo1
  namespace: test-svc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: dwflynn/demo:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
