---
apiVersion: v1
kind: Service
metadata:
  name: demo2
  namespace: test-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo_mapping
      ambassador_id: ambassador-2
      prefix: /demo/
      service: demo2.test-svc
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  joint_2_mapping
      ambassador_id: [ "ambassador-1", "ambassador-2" ]
      prefix: /demo/
      headers:
        x-demo-mode: joint
      weight: 25
      service: demo2.test-svc
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  should_not_appear_2
      prefix: /joint/
      service: demo2.test-svc
spec:
  selector:
    app: demo2
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo2
  namespace: test-svc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: dwflynn/demo:2.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
